import test from 'node:test';
import assert from 'node:assert/strict';
import { repeatabilityReport } from '../scripts/repeatability-report.mjs';
const expectedTaskIds=Array.from({length:15},(_,i)=>`task-${String(i).padStart(2,'0')}`);
const metrics={inputTokens:{sum:10,known:1,total:1},outputTokens:{sum:5,known:1,total:1},durationMs:{sum:100,known:1,total:1}};
function campaign(id,reps=1,profile='mac48') {return {id,status:'completed',split:'heldout',sourceCodeDigest:'source',configDigest:'config',catalogDigest:'catalog',rubricVersion:'rubric',provider:profile,slots:expectedTaskIds.flatMap(taskId=>Array.from({length:reps},(_,n)=>({runId:`${id}-${taskId}-${n}`,taskId,profile,status:'finished',repetition:n+1,referenceDigest:`ref-${taskId}`,grade:{passed:true,completedDeliverable:true,correctReviewOrAbstention:true},usage:{attempts:1,metrics}})))};}
const report=campaigns=>repeatabilityReport(campaigns,{expectedTaskIds});
test('one plus two repetitions combine distinct runs and preserve overlapping outcome counts',()=>{const r=report([campaign('first',1),campaign('second',2)]);const p=r.profiles[0];assert.deepEqual(r.provenance,{sourceCodeDigest:'source',configDigest:'config',catalogDigest:'catalog',rubricVersion:'rubric',split:'heldout'});assert.equal(p.runs,45);assert.equal(p.minimumThreeRunsPerTask,true);assert.equal(p.syntheticRepeatabilityQualified,true);assert.equal(p.referencePasses,45);assert.equal(p.completedDeliverables,45);assert.equal(p.correctReviewOrAbstention,45);assert.equal(p.accounting.inputTokens.sum,450);assert.equal(p.accounting.durationMs.sum,4500);assert.ok(p.tasks.every(t=>t.runs===3));});
test('distinct profiles qualify separately and absent tasks or insufficient repeats remain explicit',()=>{const a=campaign('a',3),b=campaign('b',3,'routed');b.slots=b.slots.filter(s=>s.taskId!==expectedTaskIds[14]);const r=report([a,b]);assert.equal(r.profiles[0].syntheticRepeatabilityQualified,true);const p=r.profiles[1];assert.equal(p.syntheticRepeatabilityQualified,false);assert.equal(p.tasks[14].runs,0);assert.equal(report([campaign('one')]).profiles[0].minimumThreeRunsPerTask,false);});
test('duplicate identities mismatched provenance pending work and changed references reject',()=>{const a=campaign('a');assert.throws(()=>report([a,a]),/duplicate/);for(const key of ['sourceCodeDigest','configDigest','catalogDigest','rubricVersion']){const b=campaign('b');b[key]='different';assert.throws(()=>report([a,b]),/mismatched/);}const pending=campaign('pending');pending.status='paused';assert.throws(()=>report([pending]),/completed/);const other=campaign('other');other.slots[0].referenceDigest='changed';assert.throws(()=>report([a,other]),/reference digest/);});
test('unknown outcomes and measurements remain distinct from zero and failure',()=>{const c=campaign('c',3);c.slots[0].grade={};delete c.slots[0].usage;c.slots[1].grade.passed=false;c.slots[1].usage={attempts:2,metrics:{inputTokens:{sum:10,known:1,total:2},outputTokens:{sum:null,known:0,total:2},durationMs:{sum:null,known:0,total:2}}};const p=report([c]).profiles[0];assert.equal(p.referenceFailures,1);assert.equal(p.unknownReferenceOutcomes,1);assert.equal(p.syntheticRepeatabilityQualified,false);assert.equal(p.accounting.runsMissingAttemptAccounting,1);assert.equal(p.accounting.durationMs.runsMissingMetricAccounting,1);assert.equal(p.accounting.durationMs.coverage,43/45);delete c.slots[2].referenceDigest;assert.ok(report([c]).profiles[0].reasons.includes('Missing retained reference digest'));});
