import test from 'node:test';
import assert from 'node:assert/strict';
import {routingReport} from '../scripts/routing-report.mjs';
function campaign(profile,{durations=[20,40,0],failed=false,missing=false}={}){
 return {id:profile,split:'development',status:'completed',sourceCodeDigest:'same-source',configDigest:'same-config',rubricVersion:'2.2.0',provider:profile,slots:durations.map((duration,i)=>({taskId:`volunteer_hours_reconciliation-0${i+1}`,runId:`${profile}-${i}`,profile,status:'finished',grade:{passed:!(failed&&i===1),reviewStatus:'generated_unreviewed'},usage:missing?undefined:{attempts:duration===0?0:2,unknownOutcome:0,metrics:{durationMs:{sum:duration===0?null:duration,known:duration===0?0:2,total:duration===0?0:2}}}}))};
}
test('complete successful development evidence proposes lowest measured profile',()=>{const report=routingReport([campaign('small'),campaign('large',{durations:[40,80,0]})]);assert.equal(report.proposedFamilyProfiles.participation_extract,'small');assert.equal(report.measurements[1].meanMeasuredInferenceMs,20);assert.equal(report.recommendations.find(r=>r.family==='case_extract').decision,'review');});
test('failed references remain in measured runtime but prohibit selection',()=>{const report=routingReport([campaign('fast',{durations:[10,20,0],failed:true})]);assert.equal(report.measurements[0].meanMeasuredInferenceMs,10);assert.equal(report.measurements[0].referencePasses,2);assert.equal(report.measurements[0].eligible,false);});
test('missing timing and incomplete variant coverage cannot qualify a profile',()=>{for(const c of [campaign('unknown',{missing:true}),campaign('partial',{durations:[20,40]})])assert.equal(routingReport([c]).measurements[0].eligible,false);});
test('held-out, incomplete, and incompatible campaign versions are rejected',()=>{assert.throws(()=>routingReport([{...campaign('heldout'),split:'heldout'}]),/held-out/);assert.throws(()=>routingReport([{...campaign('pending'),status:'paused'}]),/not complete/);assert.throws(()=>routingReport([campaign('a'),{...campaign('b'),sourceCodeDigest:'other'}]),/different source/);});
test('routed baseline remains visible but cannot become a model profile recommendation',()=>{const report=routingReport([campaign('routed')]);assert.equal(report.measurements[0].runs,3);assert.equal(report.measurements[0].eligible,false);assert.deepEqual(report.proposedFamilyProfiles,{});});
